# Generated by Django 4.0.5 on 2022-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
