# Generated by Django 4.0.5 on 2022-06-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_dishes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
