# Generated by Django 4.0.5 on 2022-06-13 12:45

import dishes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0005_alter_dishes_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='description',
        ),
        migrations.AddField(
            model_name='dishes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=dishes.models.get_image_filename, verbose_name='Image')),
                ('dish', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dishes.dishes')),
            ],
        ),
    ]
