# Generated by Django 4.0.5 on 2022-06-13 15:00

import dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_remove_dishes_description_dishes_user_dishimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dishes.models.get_image_filename),
        ),
    ]
