# Generated by Django 4.0.5 on 2022-06-14 11:08

import dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_alter_dishimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='user',
        ),
        migrations.AddField(
            model_name='dishes',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=dishes.models.get_image_filename),
        ),
        migrations.DeleteModel(
            name='DishImage',
        ),
    ]
