# Generated by Django 4.0.5 on 2022-06-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_remove_dishes_images_dishes_user_dish_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_images',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.dishes'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dish_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
