# Generated by Django 4.0.5 on 2022-06-15 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0010_alter_dish_images_dish_alter_dishes_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_images',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.dishes'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
