# Generated by Django 4.0.5 on 2022-06-24 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0012_alter_dish_images_dish_alter_dishes_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_Ingridients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingridients', models.CharField(max_length=255, null=True)),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.dishes')),
            ],
        ),
        migrations.CreateModel(
            name='Dish_Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.dishes')),
            ],
        ),
    ]
