# Generated by Django 4.0.5 on 2022-06-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0013_dish_ingridients_dish_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish_ingridients',
            name='dish',
        ),
        migrations.AddField(
            model_name='dishes',
            name='dish_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Dish_Description',
        ),
        migrations.DeleteModel(
            name='Dish_Ingridients',
        ),
    ]
