# Generated by Django 4.0.5 on 2022-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0014_remove_dish_ingridients_dish_dishes_dish_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dish_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
