# Generated by Django 4.0.5 on 2022-06-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0015_alter_dishes_dish_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='files')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.dishes')),
            ],
        ),
    ]
