# Generated by Django 4.1 on 2022-09-08 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0017_dishes_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish_images',
            name='dish',
        ),
        migrations.AddField(
            model_name='dishes',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishes',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Dish_Files',
        ),
        migrations.DeleteModel(
            name='Dish_Images',
        ),
    ]
