# Generated by Django 4.1 on 2022-09-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0018_remove_dish_images_dish_dishes_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dish_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
