# Generated by Django 4.1 on 2022-09-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0021_alter_category_name_alter_dishes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.category', to_field='name', verbose_name='category'),
        ),
    ]
