# Generated by Django 4.1 on 2022-09-10 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='dish_name',
        ),
        migrations.AddField(
            model_name='images',
            name='image_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
