# Generated by Django 4.1 on 2022-09-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_images_dish_name_images_image_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
